var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/client/export/route.js")
R.c("server/chunks/[root-of-the-server]__0eea15ee._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/lib_fa383252._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/[root-of-the-server]__3b18c028._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/[root-of-the-server]__9ad2eafa._.js")
R.c("server/chunks/_next-internal_server_app_api_client_export_route_actions_94e211ef.js")
R.m(80901)
module.exports=R.m(80901).exports
