var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/chat/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0381b74._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_3e969900._.js")
R.c("server/chunks/ssr/[root-of-the-server]__bb199e4a._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a5335556._.js")
R.c("server/chunks/ssr/_edb18853._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_chat_page_actions_c92d15a6.js")
R.m(20187)
module.exports=R.m(20187).exports
