// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/activity" | "/agents/[id]" | "/chat" | "/chat/[id]" | "/client" | "/costs" | "/crons" | "/docs" | "/integrations" | "/kanban" | "/login" | "/memory" | "/settings" | "/stakeholder"
type AppRouteHandlerRoutes = "/api/agents" | "/api/agents/fingerprint" | "/api/auth/[...nextauth]" | "/api/auth/preflight" | "/api/chat/[id]" | "/api/client/export" | "/api/client/summary" | "/api/conversations" | "/api/conversations/[agentId]" | "/api/costs" | "/api/cron-runs" | "/api/crons" | "/api/crons/suggestions" | "/api/drive/files" | "/api/drive/folder" | "/api/export/google-doc" | "/api/integrations" | "/api/kanban/chat-history/[ticketId]" | "/api/kanban/chat/[id]" | "/api/kanban/tickets" | "/api/kanban/work-lock" | "/api/library/config" | "/api/library/sync" | "/api/logs" | "/api/logs/stream" | "/api/memory" | "/api/memory/reindex" | "/api/onboarded" | "/api/pipelines" | "/api/stakeholder/export" | "/api/stakeholder/summary" | "/api/transcribe" | "/api/tts" | "/api/usage/stream"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/activity": {}
  "/agents/[id]": { "id": string; }
  "/api/agents": {}
  "/api/agents/fingerprint": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/preflight": {}
  "/api/chat/[id]": { "id": string; }
  "/api/client/export": {}
  "/api/client/summary": {}
  "/api/conversations": {}
  "/api/conversations/[agentId]": { "agentId": string; }
  "/api/costs": {}
  "/api/cron-runs": {}
  "/api/crons": {}
  "/api/crons/suggestions": {}
  "/api/drive/files": {}
  "/api/drive/folder": {}
  "/api/export/google-doc": {}
  "/api/integrations": {}
  "/api/kanban/chat-history/[ticketId]": { "ticketId": string; }
  "/api/kanban/chat/[id]": { "id": string; }
  "/api/kanban/tickets": {}
  "/api/kanban/work-lock": {}
  "/api/library/config": {}
  "/api/library/sync": {}
  "/api/logs": {}
  "/api/logs/stream": {}
  "/api/memory": {}
  "/api/memory/reindex": {}
  "/api/onboarded": {}
  "/api/pipelines": {}
  "/api/stakeholder/export": {}
  "/api/stakeholder/summary": {}
  "/api/transcribe": {}
  "/api/tts": {}
  "/api/usage/stream": {}
  "/chat": {}
  "/chat/[id]": { "id": string; }
  "/client": {}
  "/costs": {}
  "/crons": {}
  "/docs": {}
  "/integrations": {}
  "/kanban": {}
  "/login": {}
  "/memory": {}
  "/settings": {}
  "/stakeholder": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
