// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../app/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents/[id]">> = Specific
  const handler = {} as typeof import("../../app/agents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chat/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat/[id]">> = Specific
  const handler = {} as typeof import("../../app/chat/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/client/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client">> = Specific
  const handler = {} as typeof import("../../app/client/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/costs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/costs">> = Specific
  const handler = {} as typeof import("../../app/costs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/crons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crons">> = Specific
  const handler = {} as typeof import("../../app/crons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../app/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kanban/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kanban">> = Specific
  const handler = {} as typeof import("../../app/kanban/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory">> = Specific
  const handler = {} as typeof import("../../app/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stakeholder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stakeholder">> = Specific
  const handler = {} as typeof import("../../app/stakeholder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/fingerprint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/fingerprint">> = Specific
  const handler = {} as typeof import("../../app/api/agents/fingerprint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/preflight/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/preflight">> = Specific
  const handler = {} as typeof import("../../app/api/auth/preflight/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/chat/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/client/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/export">> = Specific
  const handler = {} as typeof import("../../app/api/client/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/client/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/summary">> = Specific
  const handler = {} as typeof import("../../app/api/client/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/[agentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[agentId]">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/[agentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/costs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/costs">> = Specific
  const handler = {} as typeof import("../../app/api/costs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron-runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron-runs">> = Specific
  const handler = {} as typeof import("../../app/api/cron-runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crons">> = Specific
  const handler = {} as typeof import("../../app/api/crons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crons/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crons/suggestions">> = Specific
  const handler = {} as typeof import("../../app/api/crons/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drive/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drive/files">> = Specific
  const handler = {} as typeof import("../../app/api/drive/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drive/folder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drive/folder">> = Specific
  const handler = {} as typeof import("../../app/api/drive/folder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/export/google-doc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/google-doc">> = Specific
  const handler = {} as typeof import("../../app/api/export/google-doc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kanban/chat-history/[ticketId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kanban/chat-history/[ticketId]">> = Specific
  const handler = {} as typeof import("../../app/api/kanban/chat-history/[ticketId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kanban/chat/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kanban/chat/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/kanban/chat/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kanban/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kanban/tickets">> = Specific
  const handler = {} as typeof import("../../app/api/kanban/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kanban/work-lock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kanban/work-lock">> = Specific
  const handler = {} as typeof import("../../app/api/kanban/work-lock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/library/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/library/config">> = Specific
  const handler = {} as typeof import("../../app/api/library/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/library/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/library/sync">> = Specific
  const handler = {} as typeof import("../../app/api/library/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logs">> = Specific
  const handler = {} as typeof import("../../app/api/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logs/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logs/stream">> = Specific
  const handler = {} as typeof import("../../app/api/logs/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/reindex/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/reindex">> = Specific
  const handler = {} as typeof import("../../app/api/memory/reindex/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory">> = Specific
  const handler = {} as typeof import("../../app/api/memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarded/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarded">> = Specific
  const handler = {} as typeof import("../../app/api/onboarded/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pipelines/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipelines">> = Specific
  const handler = {} as typeof import("../../app/api/pipelines/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stakeholder/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stakeholder/export">> = Specific
  const handler = {} as typeof import("../../app/api/stakeholder/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stakeholder/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stakeholder/summary">> = Specific
  const handler = {} as typeof import("../../app/api/stakeholder/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transcribe">> = Specific
  const handler = {} as typeof import("../../app/api/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tts">> = Specific
  const handler = {} as typeof import("../../app/api/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/usage/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage/stream">> = Specific
  const handler = {} as typeof import("../../app/api/usage/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
